/*
 * (c) Copyright 2025 Swiss Post Ltd.
 */

-- ELECTION EVENT

CREATE TABLE ELECTION_EVENT
(
    ELECTION_EVENT_ID VARCHAR2(32) NOT NULL,
    ENCRYPTION_GROUP  BLOB         NOT NULL,
    CHANGE_CONTROL_ID NUMBER(1)    NOT NULL,
    CONSTRAINT ELECTION_EVENT_PK PRIMARY KEY (ELECTION_EVENT_ID),
    CONSTRAINT ELECTION_EVENT_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE ELECTION_EVENT_STATE
(
    ELECTION_EVENT_ID VARCHAR2(32) NOT NULL,
    STATE             VARCHAR2(10) NOT NULL,
    CHANGE_CONTROL_ID NUMBER(1)    NOT NULL,
    CONSTRAINT ELECTION_EVENT_STATE_PK PRIMARY KEY (ELECTION_EVENT_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT ELECTION_EVENT_STATE_CHANGE_CK CHECK (CHANGE_CONTROL_ID <= 1)
);

CREATE TABLE CCR_RETURN_CODES_KEYS
(
    ELECTION_EVENT_ID                            VARCHAR2(32) NOT NULL,
    CCRJ_CHOICE_RETURN_CODES_ENCRYPTION_KEY_PAIR BLOB         NOT NULL,
    CCRJ_RETURN_CODES_GENERATION_SECRET_KEY      BLOB         NOT NULL,
    CCRJ_SCHNORR_PROOFS                          BLOB         NOT NULL,
    CHANGE_CONTROL_ID                            NUMBER(1)    NOT NULL,
    CONSTRAINT CCR_RETURN_CODES_KEYS_PK PRIMARY KEY (ELECTION_EVENT_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT CCR_RETURN_CODES_KEYS_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE CCM_ELECTION_KEY
(
    ELECTION_EVENT_ID      VARCHAR2(32) NOT NULL,
    CCMJ_ELECTION_KEY_PAIR BLOB         NOT NULL,
    CCMJ_SCHNORR_PROOFS    BLOB         NOT NULL,
    CHANGE_CONTROL_ID      NUMBER(1)    NOT NULL,
    CONSTRAINT CCM_ELECTION_KEY_PK PRIMARY KEY (ELECTION_EVENT_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT CCM_ELECTION_KEY_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE ELECTION_EVENT_CONTEXT
(
    ELECTION_EVENT_ID                VARCHAR2(32)             NOT NULL,
    ELECTION_EVENT_ALIAS             VARCHAR2(50)             NOT NULL,
    ELECTION_EVENT_DESCRIPTION       VARCHAR2(255)            NOT NULL,
    START_TIME                       TIMESTAMP WITH TIME ZONE NOT NULL,
    FINISH_TIME                      TIMESTAMP WITH TIME ZONE NOT NULL,
    MAX_NUMBER_OF_VOTING_OPTIONS     NUMBER(10)               NOT NULL,
    MAX_NUMBER_OF_SELECTIONS         NUMBER(10)               NOT NULL,
    MAX_NUMBER_OF_WRITE_INS_PLUS_ONE NUMBER(10)               NOT NULL,
    VOTES_TEXTS                      BLOB                     NOT NULL,
    ELECTIONS_TEXTS                  BLOB                     NOT NULL,
    CHANGE_CONTROL_ID                NUMBER(1)                NOT NULL,
    CONSTRAINT ELECTION_EVENT_CONTEXT_PK PRIMARY KEY (ELECTION_EVENT_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT ELECTION_EVENT_CONTEXT_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE EXTRACTED_ELECTION_EVENT_HASH
(
    ELECTION_EVENT_ID             VARCHAR2(32) NOT NULL,
    EXTRACTED_ELECTION_EVENT_HASH VARCHAR2(44) NOT NULL,
    CHANGE_CONTROL_ID             NUMBER(1)    NOT NULL,
    CONSTRAINT EXTRACTED_ELECTION_EVENT_HASH_PK PRIMARY KEY (ELECTION_EVENT_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT EXTRACTED_ELECTION_EVENT_HASH_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE SETUP_COMPONENT_PUBLIC_KEYS
(
    ELECTION_EVENT_ID                         VARCHAR2(32) NOT NULL,
    COMBINED_CONTROL_COMPONENT_PUBLIC_KEYS    BLOB         NOT NULL,
    ELECTORAL_BOARD_PUBLIC_KEY                BLOB         NOT NULL,
    ELECTORAL_BOARD_SCHNORR_PROOFS            BLOB         NOT NULL,
    ELECTION_PUBLIC_KEY                       BLOB         NOT NULL,
    CHOICE_RETURN_CODES_ENCRYPTION_PUBLIC_KEY BLOB         NOT NULL,
    CHANGE_CONTROL_ID                         NUMBER(1)    NOT NULL,
    CONSTRAINT SETUP_COMPONENT_PUBLIC_KEYS_PK PRIMARY KEY (ELECTION_EVENT_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT SETUP_COMPONENT_PUBLIC_KEYS_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

-- BALLOT BOXES

CREATE TABLE MIXNET_INITIAL_CIPHERTEXTS
(
    BALLOT_BOX_ID                  VARCHAR2(32)   NOT NULL,
    ENCRYPTED_CONFIRMED_VOTES_HASH VARCHAR2(1000) NOT NULL,
    MIXNET_INITIAL_CIPHERTEXTS     BLOB           NOT NULL,
    ELECTION_EVENT_FK_ID           VARCHAR2(32)   NOT NULL,
    CHANGE_CONTROL_ID              NUMBER(1)      NOT NULL,
    CONSTRAINT MIXNET_INITIAL_CIPHERTEXTS_PK PRIMARY KEY (BALLOT_BOX_ID),
    FOREIGN KEY (ELECTION_EVENT_FK_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT MIXNET_INITIAL_CIPHERTEXTS_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE MIX_DECRYPT_RESULT
(
    BALLOT_BOX_ID          VARCHAR(32) NOT NULL,
    VERIFIABLE_SHUFFLE     BLOB        NOT NULL,
    VERIFIABLE_DECRYPTIONS BLOB        NOT NULL,
    ELECTION_EVENT_FK_ID   VARCHAR(32) NOT NULL,
    CHANGE_CONTROL_ID      NUMERIC(1)  NOT NULL,
    CONSTRAINT MIX_DECRYPT_RESULT_PK PRIMARY KEY (BALLOT_BOX_ID),
    FOREIGN KEY (ELECTION_EVENT_FK_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT MIX_DECRYPT_RESULT_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

-- VERIFICATION CARD SET

CREATE TABLE VERIFICATION_CARD_SET
(
    VERIFICATION_CARD_SET_ID          VARCHAR2(32)  NOT NULL,
    VERIFICATION_CARD_SET_ALIAS       VARCHAR2(50)  NOT NULL,
    VERIFICATION_CARD_SET_DESCRIPTION VARCHAR2(255) NOT NULL,
    DOMAINS_OF_INFLUENCE              BLOB          NOT NULL,
    ELECTION_EVENT_FK_ID              VARCHAR2(32)  NOT NULL,
    CHANGE_CONTROL_ID                 NUMBER(1)     NOT NULL,
    CONSTRAINT VERIFICATION_CARD_SET_PK PRIMARY KEY (VERIFICATION_CARD_SET_ID),
    FOREIGN KEY (ELECTION_EVENT_FK_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT VERIFICATION_CARD_SET_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE LVCC_ALLOW_LIST_ENTRY
(
    LONG_VOTE_CAST_RETURN_CODE  VARCHAR2(48) NOT NULL,
    VERIFICATION_CARD_SET_FK_ID VARCHAR2(32) NOT NULL,
    CHANGE_CONTROL_ID           NUMBER(1)    NOT NULL,
    CONSTRAINT LONG_VOTE_CAST_RETURN_CODE_PK PRIMARY KEY (LONG_VOTE_CAST_RETURN_CODE),
    FOREIGN KEY (VERIFICATION_CARD_SET_FK_ID) REFERENCES VERIFICATION_CARD_SET (VERIFICATION_CARD_SET_ID),
    CONSTRAINT LONG_VOTE_CAST_RETURN_CODE_ENTITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE PCC_ALLOW_LIST_ENTRY
(
    PARTIAL_CHOICE_RETURN_CODE  VARCHAR2(44) NOT NULL,
    VERIFICATION_CARD_SET_FK_ID VARCHAR2(32) NOT NULL,
    CHUNK_ID                    NUMBER(10)   NOT NULL,
    CHANGE_CONTROL_ID           NUMBER(1)    NOT NULL,
    CONSTRAINT PARTIAL_CHOICE_RETURN_CODE_ENTITY_PK PRIMARY KEY (PARTIAL_CHOICE_RETURN_CODE),
    FOREIGN KEY (VERIFICATION_CARD_SET_FK_ID) REFERENCES VERIFICATION_CARD_SET (VERIFICATION_CARD_SET_ID),
    CONSTRAINT CHUNK_POSITIVITY_CK CHECK (CHUNK_ID >= 0),
    CONSTRAINT PARTIAL_CHOICE_RETURN_CODE_ENTITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE BALLOT_BOX
(
    BALLOT_BOX_ID               VARCHAR2(32)             NOT NULL,
    VERIFICATION_CARD_SET_FK_ID VARCHAR2(32)             NOT NULL,
    BALLOT_BOX_START_TIME       TIMESTAMP WITH TIME ZONE NOT NULL,
    BALLOT_BOX_FINISH_TIME      TIMESTAMP WITH TIME ZONE NOT NULL,
    MIXED                       CHAR(1) DEFAULT 'N'      NOT NULL,
    TEST_BALLOT_BOX             CHAR(1) DEFAULT 'N'      NOT NULL,
    NUMBER_OF_ELIGIBLE_VOTERS   NUMBER(10)               NOT NULL,
    GRACE_PERIOD                NUMBER(5)                NOT NULL,
    PRIMES_MAPPING_TABLE        BLOB                     NOT NULL,
    CHANGE_CONTROL_ID           NUMBER(1)                NOT NULL,
    CONSTRAINT BALLOT_BOX_PK PRIMARY KEY (BALLOT_BOX_ID),
    FOREIGN KEY (VERIFICATION_CARD_SET_FK_ID) REFERENCES VERIFICATION_CARD_SET (VERIFICATION_CARD_SET_ID),
    CONSTRAINT BALLOT_BOX_CHANGE_CK CHECK (CHANGE_CONTROL_ID <= 1)
);

CREATE TABLE ENCRYPTED_LONG_RETURN_CODE_SHARES
(
    CHUNK_ID                      VARCHAR(32) NOT NULL,
    VERIFICATION_CARD_SET_FK_ID   VARCHAR(32) NOT NULL,
    CONTROL_COMPONENT_CODE_SHARES BLOB        NOT NULL,
    CHANGE_CONTROL_ID             NUMERIC(1)  NOT NULL,
    CONSTRAINT ENCRYPTED_LONG_RETURN_CODE_SHARES_PK PRIMARY KEY (CHUNK_ID, VERIFICATION_CARD_SET_FK_ID),
    FOREIGN KEY (VERIFICATION_CARD_SET_FK_ID) REFERENCES VERIFICATION_CARD_SET (VERIFICATION_CARD_SET_ID),
    CONSTRAINT ENCRYPTED_LONG_RETURN_CODE_SHARES_CHANGE_CK CHECK (CHANGE_CONTROL_ID = 0)
);

-- VERIFICATION CARD

CREATE TABLE VERIFICATION_CARD
(
    VERIFICATION_CARD_ID         VARCHAR2(32) NOT NULL,
    VERIFICATION_CARD_SET_FK_ID  VARCHAR2(32) NOT NULL,
    VERIFICATION_CARD_PUBLIC_KEY BLOB         NOT NULL,
    CHANGE_CONTROL_ID            NUMBER(1)    NOT NULL,
    CONSTRAINT VERIFICATION_CARD_PK PRIMARY KEY (VERIFICATION_CARD_ID),
    FOREIGN KEY (VERIFICATION_CARD_SET_FK_ID) REFERENCES VERIFICATION_CARD_SET (VERIFICATION_CARD_SET_ID),
    CONSTRAINT VERIFICATION_CARD_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE VERIFICATION_CARD_STATE
(
    VERIFICATION_CARD_ID  VARCHAR2(32)          NOT NULL,
    PARTIALLY_DECRYPTED   CHAR(1)   DEFAULT 'N' NOT NULL,
    LCC_SHARE_CREATED     CHAR(1)   DEFAULT 'N' NOT NULL,
    CONFIRMATION_ATTEMPTS NUMBER(1) DEFAULT 0   NOT NULL,
    CONFIRMED             CHAR(1)   DEFAULT 'N' NOT NULL,
    CHANGE_CONTROL_ID     NUMBER(1)             NOT NULL,
    CONSTRAINT VERIFICATION_CARD_STATE_PK PRIMARY KEY (VERIFICATION_CARD_ID),
    FOREIGN KEY (VERIFICATION_CARD_ID) REFERENCES VERIFICATION_CARD (VERIFICATION_CARD_ID),
    CONSTRAINT VERIFICATION_CARD_STATE CHECK (CONFIRMATION_ATTEMPTS >= 0 and CONFIRMATION_ATTEMPTS <= 5)
);

CREATE TABLE PARTIALLY_DECRYPTED_PCC
(
    VERIFICATION_CARD_ID              VARCHAR2(32) NOT NULL,
    PARTIALLY_DECRYPTED_ENCRYPTED_PCC BLOB         NOT NULL,
    CHANGE_CONTROL_ID                 NUMBER(1)    NOT NULL,
    CONSTRAINT PARTIALLY_DECRYPTED_PCC_PK PRIMARY KEY (VERIFICATION_CARD_ID),
    FOREIGN KEY (VERIFICATION_CARD_ID) REFERENCES VERIFICATION_CARD (VERIFICATION_CARD_ID),
    CONSTRAINT PARTIALLY_DECRYPTED_PCC_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE LONG_CHOICE_RETURN_CODE_SHARE
(
    VERIFICATION_CARD_ID          VARCHAR(32) NOT NULL,
    LONG_CHOICE_RETURN_CODE_SHARE BLOB        NOT NULL,
    CHANGE_CONTROL_ID             NUMERIC(1)  NOT NULL,
    CONSTRAINT LONG_CHOICE_RETURN_CODE_SHARE_PK PRIMARY KEY (VERIFICATION_CARD_ID),
    FOREIGN KEY (VERIFICATION_CARD_ID) REFERENCES VERIFICATION_CARD (VERIFICATION_CARD_ID),
    CONSTRAINT LONG_CHOICE_RETURN_CODE_SHARE_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

-- Contains the exponentiated gammas and corresponding exponentiation proofs of all control components.
CREATE TABLE COMBINED_PARTIALLY_DECRYPTED_PCC
(
    VERIFICATION_CARD_ID             VARCHAR2(32) NOT NULL,
    COMBINED_PARTIALLY_DECRYPTED_PCC BLOB         NOT NULL,
    CHANGE_CONTROL_ID                NUMBER(1)    NOT NULL,
    CONSTRAINT COMBINED_PARTIALLY_DECRYPTED_PCC_PK PRIMARY KEY (VERIFICATION_CARD_ID),
    FOREIGN KEY (VERIFICATION_CARD_ID) REFERENCES VERIFICATION_CARD (VERIFICATION_CARD_ID),
    CONSTRAINT COMBINED_PARTIALLY_DECRYPTED_PCC_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE LONG_VOTE_CAST_RETURN_CODE_SHARE
(
    VERIFICATION_CARD_ID                    VARCHAR2(32)   NOT NULL,
    CONFIRMATION_KEY                        VARCHAR2(1000) NOT NULL,
    LONG_VOTE_CAST_RETURN_CODE_SHARE        BLOB           NOT NULL,
    HASHED_LONG_VOTE_CAST_RETURN_CODE_SHARE VARCHAR2(1000) NOT NULL,
    CONFIRMATION_ATTEMPT_ID                 NUMBER(1)      NOT NULL,
    CHANGE_CONTROL_ID                       NUMBER(1)      NOT NULL,
    CONSTRAINT LONG_VOTE_CAST_RETURN_CODE_SHARE_PK PRIMARY KEY (VERIFICATION_CARD_ID, CONFIRMATION_ATTEMPT_ID),
    FOREIGN KEY (VERIFICATION_CARD_ID) REFERENCES VERIFICATION_CARD (VERIFICATION_CARD_ID),
    CONSTRAINT LONG_VOTE_CAST_RETURN_CODE_SHARE_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0),
    CONSTRAINT LONG_VOTE_CAST_RETURN_CODE_SHARE_ATTEMPTS_CK CHECK (CONFIRMATION_ATTEMPT_ID >= 0 and CONFIRMATION_ATTEMPT_ID < 5)
);

-- Contains the hashed long Vote Cast Return Code shares of all control components.
CREATE TABLE HASHED_LONG_VOTE_CAST_RETURN_CODE_SHARES
(
    VERIFICATION_CARD_ID                     VARCHAR2(32)        NOT NULL,
    HASHED_LONG_VOTE_CAST_RETURN_CODE_SHARES BLOB                NOT NULL,
    IS_VERIFIED                              CHAR(1) DEFAULT 'N' NOT NULL,
    CHANGE_CONTROL_ID                        NUMBER(1)           NOT NULL,
    CONSTRAINT HASHED_LONG_VOTE_CAST_RETURN_CODE_SHARES_PK PRIMARY KEY (VERIFICATION_CARD_ID),
    FOREIGN KEY (VERIFICATION_CARD_ID) REFERENCES VERIFICATION_CARD (VERIFICATION_CARD_ID),
    CONSTRAINT HASHED_LONG_VOTE_CAST_RETURN_CODE_SHARES_CK CHECK (CHANGE_CONTROL_ID <= 5)
);

CREATE TABLE ENCRYPTED_VERIFIABLE_VOTE
(
    VERIFICATION_CARD_ID                  VARCHAR2(32) NOT NULL,
    CONTEXT_IDS                           BLOB         NOT NULL,
    ENCRYPTED_VOTE                        BLOB         NOT NULL,
    EXPONENTIATED_ENCRYPTED_VOTE          BLOB         NOT NULL,
    ENCRYPTED_PARTIAL_CHOICE_RETURN_CODES BLOB         NOT NULL,
    EXPONENTIATION_PROOF                  BLOB         NOT NULL,
    PLAINTEXT_EQUALITY_PROOF              BLOB         NOT NULL,
    CHANGE_CONTROL_ID                     NUMBER(1)    NOT NULL,
    CONSTRAINT ENCRYPTED_VERIFIABLE_VOTE_PK PRIMARY KEY (VERIFICATION_CARD_ID),
    FOREIGN KEY (VERIFICATION_CARD_ID) REFERENCES VERIFICATION_CARD (VERIFICATION_CARD_ID),
    CONSTRAINT ENCRYPTED_VERIFIABLE_VOTE_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

-- TECHNICAL

CREATE TABLE COMMAND
(
    CONTEXT_ID            VARCHAR2(255)     NOT NULL,
    CONTEXT               VARCHAR2(255)     NOT NULL,
    CORRELATION_ID        VARCHAR2(255)     NOT NULL,
    NODE_ID               NUMBER(1)         NOT NULL,
    REQUEST_PAYLOAD_HASH  VARCHAR2(45 CHAR) NOT NULL,
    REQUEST_TIMESTAMP     TIMESTAMP(6)      NOT NULL,
    RESPONSE_PAYLOAD_HASH VARCHAR2(45 CHAR) NOT NULL,
    RESPONSE_PAYLOAD      BLOB              NOT NULL,
    RESPONSE_TIMESTAMP    TIMESTAMP(6)      NOT NULL,
    CHANGE_CONTROL_ID     NUMBER(1)         NOT NULL,
    PRIMARY KEY (CONTEXT_ID, CONTEXT, CORRELATION_ID, NODE_ID),
    CONSTRAINT COMMAND_UK UNIQUE (CONTEXT_ID, CONTEXT, NODE_ID),
    CONSTRAINT COMMAND_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);
