# This version must be aligned with the version of the maven artemis-jakarta-client dependency.
FROM apache/activemq-artemis:2.44.0-alpine@sha256:1bce124d2324faeb1253e2db4bb68d64decf46412ecfd8d9ef46c08b1b4af5b4

ENTRYPOINT ["/docker-run.sh"]
CMD ["run"]
