/*
 * (c) Copyright 2025 Swiss Post Ltd.
 */

-- ELECTION EVENT

CREATE TABLE ELECTION_EVENT
(
    ELECTION_EVENT_ID VARCHAR(32) NOT NULL,
    ENCRYPTION_GROUP  BYTEA       NOT NULL,
    CHANGE_CONTROL_ID NUMERIC(1)  NOT NULL,
    CONSTRAINT ELECTION_EVENT_PK PRIMARY KEY (ELECTION_EVENT_ID),
    CONSTRAINT ELECTION_EVENT_IMMUTABILITY_CK CHECK ( CHANGE_CONTROL_ID = 0 )
);

CREATE TABLE ELECTION_EVENT_CONTEXT
(
    ELECTION_EVENT_ID          VARCHAR(32)              NOT NULL,
    START_TIME                 TIMESTAMP WITH TIME ZONE NOT NULL,
    FINISH_TIME                TIMESTAMP WITH TIME ZONE NOT NULL,
    ELECTION_EVENT_ALIAS       VARCHAR(50)              NOT NULL,
    ELECTION_EVENT_DESCRIPTION VARCHAR(255)             NOT NULL,
    VOTES_TEXTS                BYTEA                    NOT NULL,
    ELECTIONS_TEXTS            BYTEA                    NOT NULL,
    CHANGE_CONTROL_ID          NUMERIC(1)               NOT NULL,
    CONSTRAINT ELECTION_EVENT_CONTEXT_PK PRIMARY KEY (ELECTION_EVENT_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT ELECTION_EVENT_CONTEXT_IMMUTABILITY_CK CHECK ( CHANGE_CONTROL_ID = 0 )
);

CREATE TABLE SETUP_COMPONENT_PUBLIC_KEYS
(
    ELECTION_EVENT_ID                         VARCHAR(32) NOT NULL,
    CHOICE_RETURN_CODES_ENCRYPTION_PUBLIC_KEY BYTEA       NOT NULL,
    COMBINED_CONTROL_COMPONENT_PUBLIC_KEYS    BYTEA       NOT NULL,
    ELECTION_PUBLIC_KEY                       BYTEA       NOT NULL,
    ELECTORAL_BOARD_PUBLIC_KEY                BYTEA       NOT NULL,
    ELECTORAL_BOARD_SCHNORR_PROOFS            BYTEA       NOT NULL,
    CHANGE_CONTROL_ID                         NUMERIC(1)  NOT NULL,
    CONSTRAINT SETUP_COMPONENT_PUBLIC_KEYS_PK PRIMARY KEY (ELECTION_EVENT_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT SETUP_COMPONENT_PUBLIC_KEYS_IMMUTABILITY_CK CHECK ( CHANGE_CONTROL_ID = 0 )
);

-- BALLOT BOXES

CREATE TABLE CONTROL_COMPONENT_BALLOT_BOX_PAYLOAD
(
    ELECTION_EVENT_ID VARCHAR(32) NOT NULL,
    BALLOT_BOX_ID     VARCHAR(32) NOT NULL,
    NODE_ID           NUMERIC(1)  NOT NULL,
    PAYLOAD           BYTEA       NOT NULL,
    CHANGE_CONTROL_ID NUMERIC(1)  NOT NULL,
    CONSTRAINT CONTROL_COMPONENT_BALLOT_BOX_PAYLOAD_PK PRIMARY KEY (ELECTION_EVENT_ID, BALLOT_BOX_ID, NODE_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT CONTROL_COMPONENT_BALLOT_BOX_PAYLOAD_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE CONTROL_COMPONENT_VOTES_HASH_PAYLOAD
(
    ELECTION_EVENT_ID VARCHAR(32) NOT NULL,
    BALLOT_BOX_ID     VARCHAR(32) NOT NULL,
    NODE_ID           NUMERIC(1)  NOT NULL,
    PAYLOAD           BYTEA       NOT NULL,
    CHANGE_CONTROL_ID NUMERIC(1)  NOT NULL,
    CONSTRAINT CONTROL_COMPONENT_VOTES_HASH_PAYLOAD_PK PRIMARY KEY (ELECTION_EVENT_ID, BALLOT_BOX_ID, NODE_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT CONTROL_COMPONENT_VOTES_HASH_PAYLOAD_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

CREATE TABLE CONTROL_COMPONENT_SHUFFLE_PAYLOAD
(
    ELECTION_EVENT_ID VARCHAR(32) NOT NULL,
    BALLOT_BOX_ID     VARCHAR(32) NOT NULL,
    NODE_ID           NUMERIC(1)  NOT NULL,
    PAYLOAD           BYTEA       NOT NULL,
    CHANGE_CONTROL_ID NUMERIC(1)  NOT NULL,
    CONSTRAINT SHUFFLE_PAYLOAD_PK PRIMARY KEY (ELECTION_EVENT_ID, BALLOT_BOX_ID, NODE_ID),
    FOREIGN KEY (ELECTION_EVENT_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT SHUFFLE_PAYLOAD_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);

-- VERIFICATION CARD SET

CREATE TABLE VERIFICATION_CARD_SET
(
    VERIFICATION_CARD_SET_ID          VARCHAR(32)  NOT NULL,
    VERIFICATION_CARD_SET_ALIAS       VARCHAR(50)  NOT NULL,
    VERIFICATION_CARD_SET_DESCRIPTION VARCHAR(255) NOT NULL,
    DOMAINS_OF_INFLUENCE              BYTEA        NOT NULL,
    ELECTION_EVENT_FK_ID              VARCHAR(32)  NOT NULL,
    CHANGE_CONTROL_ID                 NUMERIC(1)   NOT NULL,
    CONSTRAINT VERIFICATION_CARD_SET_PK PRIMARY KEY (VERIFICATION_CARD_SET_ID),
    FOREIGN KEY (ELECTION_EVENT_FK_ID) REFERENCES ELECTION_EVENT (ELECTION_EVENT_ID),
    CONSTRAINT VERIFICATION_CARD_SET_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);


CREATE TABLE BALLOT_BOX
(
    BALLOT_BOX_ID               VARCHAR(32)              NOT NULL,
    VERIFICATION_CARD_SET_FK_ID VARCHAR(32)              NOT NULL,
    BALLOT_BOX_START_TIME       TIMESTAMP WITH TIME ZONE NOT NULL,
    BALLOT_BOX_FINISH_TIME      TIMESTAMP WITH TIME ZONE NOT NULL,
    MIXED                       CHAR(1) DEFAULT 'N'      NOT NULL,
    TEST_BALLOT_BOX             CHAR(1) DEFAULT 'N'      NOT NULL,
    GRACE_PERIOD                NUMERIC(5)               NOT NULL,
    PRIMES_MAPPING_TABLE        BYTEA                    NOT NULL,
    CHANGE_CONTROL_ID           NUMERIC(1)               NOT NULL,
    CONSTRAINT BALLOT_BOX_PK PRIMARY KEY (BALLOT_BOX_ID),
    FOREIGN KEY (VERIFICATION_CARD_SET_FK_ID) REFERENCES VERIFICATION_CARD_SET (VERIFICATION_CARD_SET_ID),
    CONSTRAINT GRACE_PERIOD_POSITIVITY_CK CHECK (GRACE_PERIOD >= 0),
    CONSTRAINT BALLOT_BOX_CHANGE_CK CHECK (CHANGE_CONTROL_ID <= 1)
);

CREATE TABLE RETURN_CODES_MAPPING_TABLE_ENTRY
(
    VERIFICATION_CARD_SET_ID    VARCHAR(32) NOT NULL,
    HASHED_LONG_RETURN_CODE     VARCHAR(44) NOT NULL,
    ENCRYPTED_SHORT_RETURN_CODE VARCHAR(48) NOT NULL,
    CHANGE_CONTROL_ID           NUMERIC(1)  NOT NULL,
    CONSTRAINT RETURN_CODES_MAPPING_TABLE_ENTRY_PK PRIMARY KEY (HASHED_LONG_RETURN_CODE),
    FOREIGN KEY (VERIFICATION_CARD_SET_ID) REFERENCES VERIFICATION_CARD_SET (VERIFICATION_CARD_SET_ID),
    CONSTRAINT RETURN_CODES_MAPPING_TABLE_ENTRY_CK CHECK ( CHANGE_CONTROL_ID = 0 )
);

CREATE TABLE ENC_LONG_CODE_SHARE
(
    VERIFICATION_CARD_SET_ID VARCHAR(32) NOT NULL,
    CHUNK_ID                 NUMERIC(10) NOT NULL,
    NODE_ID                  NUMERIC(1)  NOT NULL,
    ENC_LONG_CODE_SHARE      BYTEA       NOT NULL,
    CHANGE_CONTROL_ID        NUMERIC(1)  NOT NULL,
    CONSTRAINT ENC_LONG_CODE_SHARE_PK PRIMARY KEY (VERIFICATION_CARD_SET_ID, CHUNK_ID, NODE_ID),
    FOREIGN KEY (VERIFICATION_CARD_SET_ID) REFERENCES VERIFICATION_CARD_SET (VERIFICATION_CARD_SET_ID),
    CONSTRAINT ENC_LONG_CODE_SHARE_IMMUTABILITY_CK CHECK (CHANGE_CONTROL_ID = 0)
);
CREATE SEQUENCE ENC_LONG_CODE_SHARE_SEQ;

/*
 * (c) Copyright 2025 Swiss Post Ltd.
 */

-- VERIFICATION CARD

CREATE TABLE VERIFICATION_CARD
(
    VERIFICATION_CARD_ID        VARCHAR(32) NOT NULL,
    VERIFICATION_CARD_SET_FK_ID VARCHAR(32) NOT NULL,
    CREDENTIAL_ID               VARCHAR(32) NOT NULL UNIQUE,
    VOTING_CARD_ID              VARCHAR(32) NOT NULL,
    VOTER_AUTHENTICATION_DATA   BYTEA       NOT NULL,
    CHANGE_CONTROL_ID           NUMERIC(1)  NOT NULL,
    CONSTRAINT VERIFICATION_CARD_PK PRIMARY KEY (VERIFICATION_CARD_ID),
    FOREIGN KEY (VERIFICATION_CARD_SET_FK_ID) REFERENCES VERIFICATION_CARD_SET (VERIFICATION_CARD_SET_ID),
    CONSTRAINT VERIFICATION_CARD_IMMUTABILITY_CK CHECK ( CHANGE_CONTROL_ID = 0 )
);
CREATE UNIQUE INDEX VOTING_CARD_ID_UK1 ON VERIFICATION_CARD (VOTING_CARD_ID);

CREATE TABLE SETUP_COMPONENT_VERIFICATION_CARD_KEYSTORE
(
    VERIFICATION_CARD_ID       VARCHAR(32) NOT NULL,
    VERIFICATION_CARD_KEYSTORE BYTEA       NOT NULL,
    CHANGE_CONTROL_ID          NUMERIC(1)  NOT NULL,
    CONSTRAINT SETUP_COMPONENT_VERIFICATION_CARD_KEYSTORE_PK PRIMARY KEY (VERIFICATION_CARD_ID),
    FOREIGN KEY (VERIFICATION_CARD_ID) REFERENCES VERIFICATION_CARD (VERIFICATION_CARD_ID),
    CONSTRAINT SETUP_COMPONENT_VERIFICATION_CARD_KEYSTORE_IMMUTABILITY_CK CHECK ( CHANGE_CONTROL_ID = 0 )
);

CREATE TABLE VERIFICATION_CARD_STATE
(
    VERIFICATION_CARD_ID                     VARCHAR(32)              NOT NULL,
    SHORT_CHOICE_RETURN_CODES                BYTEA,
    SHORT_VOTE_CAST_RETURN_CODE              VARCHAR(8),
    STATE                                    NUMERIC(1)               NOT NULL,
    AUTHENTICATION_ATTEMPTS                  NUMERIC(1)               NOT NULL,
    LAST_SUCCESSFUL_AUTHENTICATION_TIME_STEP NUMERIC(19)              NOT NULL,
    SUCCESSFUL_AUTHENTICATION_ATTEMPTS       BYTEA                    NOT NULL,
    CONFIRMATION_ATTEMPTS                    NUMERIC(1)               NOT NULL,
    STATE_DATE                               TIMESTAMP WITH TIME ZONE NOT NULL,
    CHANGE_CONTROL_ID                        NUMERIC(10)              NOT NULL,
    CONSTRAINT VERIFICATION_CARD_STATE_PK PRIMARY KEY (VERIFICATION_CARD_ID),
    FOREIGN KEY (VERIFICATION_CARD_ID) REFERENCES VERIFICATION_CARD (VERIFICATION_CARD_ID),
    CONSTRAINT VERIFICATION_CARD_STATE CHECK (CONFIRMATION_ATTEMPTS >= 0 and CONFIRMATION_ATTEMPTS <= 5)
);

-- TECHNICAL

CREATE TABLE IDEMPOTENT_EXECUTION
(
    CONTEXT           VARCHAR(255) NOT NULL,
    EXECUTION_KEY     VARCHAR(255) NOT NULL,
    PAYLOAD_HASH      VARCHAR(45)  NOT NULL,
    CHANGE_CONTROL_ID NUMERIC(1)   NOT NULL,
    CONSTRAINT IDEMPOTENT_EXECUTION_PK PRIMARY KEY (CONTEXT, EXECUTION_KEY),
    CONSTRAINT IDEMPOTENT_EXECUTION_IMMUTABILITY_CK CHECK ( CHANGE_CONTROL_ID = 0 )
);

CREATE TABLE QUEUED_COMPUTE_CHUNK_IDS_ENTITY
(
    ELECTION_EVENT_ID        VARCHAR(32) NOT NULL,
    VERIFICATION_CARD_SET_ID VARCHAR(32) NOT NULL,
    CHUNK_ID                 NUMERIC(10) NOT NULL,
    CONSTRAINT QUEUED_COMPUTE_CHUNK_IDS_ENTITY_PK PRIMARY KEY (ELECTION_EVENT_ID, VERIFICATION_CARD_SET_ID, CHUNK_ID)
);

CREATE TABLE IN_PROGRESS_MESSAGE
(
    CORRELATION_ID        VARCHAR(255) NOT NULL,
    NODE_ID               NUMERIC(1)   NOT NULL,
    REQUEST_MESSAGE_TYPE  VARCHAR(255) NOT NULL,
    CONTEXT_ID            VARCHAR(255) NOT NULL,
    RESPONSE_MESSAGE_TYPE VARCHAR(255),
    RESPONSE_PAYLOAD      BYTEA,
    CONSTRAINT IN_PROGRESS_MESSAGE_PK PRIMARY KEY (CORRELATION_ID, NODE_ID),
    CONSTRAINT IN_PROGRESS_MESSAGE_UK1 UNIQUE (REQUEST_MESSAGE_TYPE, CONTEXT_ID, NODE_ID)
);

CREATE TABLE WORKFLOW_SHELF
(
    ID            VARCHAR(100)             NOT NULL,
    SHELF_DATA    BYTEA                    NOT NULL,
    CREATION_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT WORKFLOW_SHELF_PK PRIMARY KEY (ID)
);

CREATE TABLE VOTER_PORTAL_CONFIGURATION
(
    ELECTION_EVENT_ID VARCHAR(32) NOT NULL,
    CONFIG            BYTEA       NOT NULL,
    FAVICON           BYTEA       NOT NULL,
    LOGO              BYTEA       NOT NULL,
    CHANGE_CONTROL_ID NUMERIC(3)  NOT NULL,
    CONSTRAINT VOTER_PORTAL_CONFIGURATION_PK PRIMARY KEY (ELECTION_EVENT_ID)
);
