/*
 * (c) Copyright 2025 Swiss Post Ltd.
 */
package ch.post.it.evoting.controlcomponent.commandmessaging;

public enum Context {
	MIXING_TALLY_MIX_DEC_ONLINE,
	MIXING_TALLY_GET_MIXNET_INITIAL_CIPHERTEXTS,
	CONFIGURATION_RETURN_CODES_GEN_ENC_LONG_CODE_SHARES,
	CONFIGURATION_RETURN_CODES_GEN_KEYS_CCR,
	VOTING_RETURN_CODES_CREATE_LCC_SHARE,
	VOTING_RETURN_CODES_CREATE_LVCC_SHARE_HASH,
	VOTING_RETURN_CODES_VERIFY_LVCC_SHARE_HASH,
	VOTING_RETURN_CODES_PARTIAL_DECRYPT_PCC,
	CONFIGURATION_SETUP_COMPONENT_PUBLIC_KEYS,
	CONFIGURATION_SETUP_VOTING_LONG_VOTE_CAST_RETURN_CODES_ALLOW_LIST
}
